language: go

script:
        - go get github.com/schollz/boltdb-server/...
        - cd $GOPATH/src/github.com/schollz/boltdb-server && go build
        - cd $GOPATH/src/github.com/schollz/boltdb-server && ./boltdb-server &
        - cd $GOPATH/src/github.com/schollz/boltdb-server/connect && go test
